### ISSUE TITLE
Delete prompt not getting cleared correctly

### ISSUE THREAD

**Issue by muskan1109** [Aravinthyan/KeepSafe#11]
When the user goes to delete a service, the confirmation message appears on the right-hand-side of the application. However, in the case where the user has clicked on the wrong service by mistake, when they go to the search bar to look for the correct service, the confirmation message for the previously selected service does not get cleared. Please find images for reference.

![image_1](https://user-images.githubusercontent.com/65097946/136674182-ff4ec750-dab9-44df-b2eb-2ca8d150085e.png)
![image_2](https://user-images.githubusercontent.com/65097946/136674191-e37bcf64-ab4f-49fa-94a4-842236e40ad5.png)

**Comment by Aravinthyan** [comment]
This is an issue that is also present in the search tab as well. Will be fixed along with this.

**Comment by Aravinthyan** [comment]
This has been merged, d41c1768ca871c4529ad622dd6b12fc1154fcc81. Will be released with v0.1.0.
